export const actionTypes = {
  TOGGLE_CART_VISIBILITY: 'TOGGLE_CART_VISIBILITY',
  SET_CART_VISIBILITY: 'SET_CART_VISIBILITY',
  ADD_CART_ITEM: 'ADD_CART_ITEM',
  REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
};
